version: '3'
services:
  api:
    container_name: fastAPI
    restart: on-failure
    ports:
      - target: 4343
        published: 8080
        protocol: tcp
        mode: host
    build:
      context: .
        # dockerfile: Dockerfile
      dockerfile: Dockerfile.pipenv
        # deploy:
        #   resources:
        #     limits:
        #       cpus: '0.5'
        #     memory: 100M
        #   reservations:
        #     cpus: '0.5'
        #     memory: 100M





