FROM python:3.10
MAINTAINER Nariman Huseynov "hnariman@gmail.com"

WORKDIR /server

RUN pip install pipenv

COPY ./Pipfile*  /server/
RUN pipenv install --system --deploy --ignore-pipfile

COPY . /server/
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "4343"]
